import = ["~/.config/alacritty/themes/catppuccin_mocha.toml"]

[env]
term = "xterm-256color"

[window]
dimensions.columns = 100
dimensions.lines = 25

[font]
normal = {family = "JetBrainsMono NF"}
size = 11.5

[selection]
save_to_clipboard = true
