import = ["~/.config/alacritty/themes/catppuccin_mocha.toml"]

[env]
term = "xterm-256color"

[window]
dimensions.columns = 120
dimensions.lines = 30
opacity = 1

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 10

[selection]
save_to_clipboard = true
